# Generated by Django 4.0.5 on 2022-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, unique=True)),
                ('EstiloCombate', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, unique=True)),
                ('EstiloCombate', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
