# Generated by Django 4.0.5 on 2022-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatos',
            name='Ataque',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='gatos',
            name='Evasion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='gatos',
            name='ProbabilidadCritico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='gatos',
            name='PuntosVida',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name='perros',
            name='Ataque',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='perros',
            name='Evasion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='perros',
            name='ProbabilidadCritico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='perros',
            name='PuntosVida',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4),
        ),
    ]
